### ISSUE TITLE
dumb question, VerifyMessageProviderRaw() func does not look like it supports real async messaging

### ISSUE THREAD

**Issue by singlaive** [pact-foundation/pact-go#111]
I might misunderstand in the first place. When pact go claims it supports async messaging API, I thought it would build some abstract layer on top of major messaging protocol amqp, stomp, openwire etc. and verify API behaviours via send/receive messages.
But when reading the source code like VerifyMessageProviderRaw() function, it seems it mimic messaging by plain http?
Was I totally missing anything?

**Comment by mefellows** [comment]
Rather than try and implement _every_ type of messaging, async provider, our philosophy is to test what matters - the message exchanged between them. You don't need Pact to check that the stomp library you're using works correctly - you just want to ensure that the systems at either end can read each others' messages.

So we encourage separating the protocol handling from the message exchange in your code. This way, you can test them quite easily and separately with appropriate tools.

See https://github.com/pact-foundation/pact-go#asynchronous-api-testing and the articles linked from them for more details.
