### ISSUE TITLE
Include a GraphQL interace in Pact-go 

### ISSUE THREAD

**Issue by Sarek-Wyona** [pact-foundation/pact-go#195]
Currently pact-go does not have an Graph-QL interface similar to what is provided by the pact-js library. Can this please be added so that we could leverage pact for graphql testing too. 

Having an example https://github.com/pact-foundation/pact-js/tree/master/examples/graphql such as this would be extremely useful.

**Comment by mefellows** [comment]
Please see the draft PR #200 that has a firs cut at this. I'd really appreciate some early feedback on this.

The provider side shouldn’t need anything, because as far as it’s concerned, it should just accept the HTTP request and respond as needed. It's just the consumer side that needs an API exposed.

In the example added, I found the hasura GraphQL [client](https://github.com/hasura/go-graphql-client/) a bit unfriendly to use, in that I still had to hard-code the GraphQL query in the test - there was no way to programmatically get it to print out what query it would make. I would ideally like to not have to specify it by hand, as I can see that not being an ideal experience for developers to have to write.

**Comment by ravindradhaka** [comment]
@mefellows Could You pls Merge this mr in master so that we can use graphql Interface in go-pacts

**Comment by mefellows** [comment]
Done :)

Released in 1.7.0.
