### ISSUE TITLE
enhancement: notify if installing on Alpine

### ISSUE THREAD

**Issue by mefellows** [pact-foundation/pact-go#233]
Alpine is not officially supported, and is fraught with problems due to its use of musl over glibc.

See also https://github.com/pact-foundation/pact-net/issues/387#issuecomment-1114365283.

If we can detect the alpine OS at `pact-go install` (or other CLI calls) we could print out a notice warning users of potential issues.

**Comment by ramanverma2k** [comment]
Hi!
I would like to work on this issue but i am not quite sure how to approach it correctly. I do have a working solution currently ready but before opening a pr, I thought it would be best to discuss about more.

My current approach and solution is like this :-
1. Check if the OS is Linux.
2. Look for sh shell in the OS environment path.
3. Grep the OS ID from /etc/*-release
4. Check whether the ID is alpine.
5. Print an Info message if it is otherwise continue on checking installation and binaries.

All of those steps happen on running **pact-go install**

My concerns about the above approach :-
1. What if sh shell does not exist on the system? Should we fall back to a different shell?
2. Isn't there any better way other than grep-ing the system info through a shell?

**Comment by mefellows** [comment]
Thanks for picking this up - much appreciated!

What's the point of step (2) sorry?

> Print an Info message if it is otherwise continue on checking installation and binaries.

I think we should print a `WARN` level here, even if the user has compiled their own alpine target of the library. What do you think?

The main issue with alpine is not simply alpine, but it's use of the musl library. So another approach could be to detect the presence of musl (or absence of glibc). There are various ways to do that, but executing `ldd` on any known binary and then doing a string match (in golang) on the result should be enough to detect the presence of musl, and warn about it.

**Comment by ramanverma2k** [comment]
Thank you for the input!

> What's the point of step (2) sorry?
> 
> > Print an Info message if it is otherwise continue on checking installation and binaries.
> 
> I think we should print a `WARN` level here, even if the user has compiled their own alpine target of the library. What do you think?

I was printing the ``INFO`` level message while testing my implementation and did not really pay attention that much. Now that you have pointed it out, It does make a lot of sense to just print out a ``WARN`` level message. I will keep that in mind.


> The main issue with alpine is not simply alpine, but it's use of the musl library. So another approach could be to detect the presence of musl (or absence of glibc). There are various ways to do that, but executing `ldd` on any known binary and then doing a string match (in golang) on the result should be enough to detect the presence of musl, and warn about it.

I see, this approach is way better than mine. Thanks!

**Comment by mefellows** [comment]
No worries, thanks!

**Comment by ramanverma2k** [comment]
Solution merged in #246
