### ISSUE TITLE
Need the release date for all the fixes of the vulnerabilities for this library

### ISSUE THREAD

**Issue by VineetMaheshwari** [pact-foundation/pact-go#287]
We are using this repo for performing pact testing using Golang but have overserved that the last stable released v1.7.0 contains the following vulnerabilities associated with it:

![image](https://user-images.githubusercontent.com/28062414/235628241-d55d04f5-a444-4e96-aae4-5d8d934717f4.png)

Are all these vulnerabilities resolveable? If yes, by when can we expect a release with all the vulnerabilities fixes

**Comment by mefellows** [comment]
Have you tried updating them and seeing if the issues are resolved?
I can't see how there is any material security vulnerabilities in the way they are used in this library - they aren't used in a runtime / deployed app.

**Comment by YOU54F** [comment]
>Are all these vulnerabilities resolveable? 

You are welcome too, and encouraged to fork the repo, update the dependencies or resolve any issues, and propose a PR.

>If yes, by when can we expect a release with all the vulnerabilities fixes

Regarding, if yes, unsure without investigation. It would be helpful to maintainers if you could

1) ascertain if and how the issues would affect our end users
2) propose fixes to resolve the issues

>when can we expect a release with all the vulnerabilities fixes

The maintainer would appreciate help in providing fixes for these vulnerabilities, otherwise it would be when the maintainer has capacity, and no-one works on pact-go as a full time job.

**Comment by mefellows** [comment]
Closing due to non-response.
