### ISSUE TITLE
golangci-lint failing against master branch

### ISSUE THREAD

**Issue by YOU54F** [pact-foundation/pact-go#320]
golangci-lint is failing against the `master` branch

#310 will fix the build such that golangci-lint can run successfully.

This has highlighted linting errors in the `master` branch which now need resolving :)

This issue is to track. Contributions are welcome (Go isn't my strongest language!)

**Comment by boreyuk** [comment]
Hi ! I took a look at the errors raised by golangci-lint. Most of the errors is due to not checking error values returned by functions. For the moment, I explicitely ignored most of the errors returned, in order to not change the current behavior. However, I think that some errors should be managed. I put a "TODO" comment on these errors in my PR.

Feel free to review and give feedback :-)

**Comment by YOU54F** [comment]
Resolved thanks to @boreyuk!

Viva la community
