### ISSUE TITLE
0.0.14-beta breaking changes

### ISSUE THREAD

**Issue by zbintliff** [pact-foundation/pact-go#94]
It removes `dsl.Pact.Port` field causing builds to work. 

Old versions of `glide` incorrectly pull `-beta` and `-alpha` tags. My problem is fixed by updating glide but figured you would want to know it _is_ a breaking change.

**Comment by mefellows** [comment]
Thanks @zbintliff, yes this is good info for us.

Sorry to hear the beta tags get pulled in by default. 

As an aside, you might want to check out the `1.x.x` branch which is where the bulk of changes/features are (and have been) going.

`0.x.x` is essentially deprecated, with just compatible bug fixes being backported to it.

**Comment by zbintliff** [comment]
Yup, its in our backlog to convert over and we are excited to try it out!

**Comment by mefellows** [comment]
Hmm, something has gone awry in the build process. It seems to have released the correct binary package to GitHub, but _tagged_ the master branch (which is why you're seeing the removal of that field).

I'm continually rueing my decision to use Wercker - even after migrating away from it for the `1.x.x` branch!!

**Comment by mefellows** [comment]
This is sorted now with the new build and tagging process via Travis, closing this.
